# Generated by Django 6.0 on 2025-12-17 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(choices=[('fa-star', 'Star'), ('fa-fire', 'Fire'), ('fa-rocket', 'Rocket'), ('fa-target', 'Target'), ('fa-gem', 'Gem'), ('fa-trophy', 'Trophy'), ('fa-crown', 'Crown'), ('fa-lightning-bolt', 'Lightning')], max_length=30)),
                ('color_class', models.CharField(choices=[('from-blue-500 to-blue-600', 'Blue'), ('from-purple-500 to-purple-600', 'Purple'), ('from-green-500 to-green-600', 'Green'), ('from-pink-500 to-pink-600', 'Pink'), ('from-orange-500 to-orange-600', 'Orange'), ('from-red-500 to-red-600', 'Red')], max_length=50)),
                ('points', models.IntegerField(default=10)),
                ('criterion', models.CharField(help_text="Trigger condition: e.g., 'first_application', 'five_applications', 'offer_received'", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumeapp.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-unlocked_at'],
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
