# Generated by Django 6.0 on 2025-12-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0002_achievement_userachievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='source',
            field=models.CharField(blank=True, choices=[('linkedin', 'LinkedIn'), ('indeed', 'Indeed'), ('glassdoor', 'Glassdoor'), ('company_website', 'Company Website'), ('recruiter', 'Recruiter'), ('referral', 'Referral'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='work_setup',
            field=models.CharField(blank=True, choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('on-site', 'On-site'), ('flexible', 'Flexible')], default='flexible', max_length=20),
        ),
    ]
